; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev

[common]
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39
board = esp32dev
board_build.partitions = custom_partitions.csv
extra_scripts = pre:scripts/generate_headers.py
build_flags =
	-DVERSION_MAJOR=3
	-DVERSION_MINOR=7
	-DWEBAPPVER_MAJOR=3
	-DWEBAPPVER_MINOR=4
	-DCORE_DEBUG_LEVEL=0
	-DGITHUBAPIHOST='"api.github.com"'
	-DGITHUBTOKEN='""'
	-DGITHUBREPOPATH='"/repos/gadec-uk/departures-board/releases/latest"'
	-DU8G2_WITHOUT_FONT_ROTATION
	-DU8G2_WITHOUT_UNICODE
board_build.f_cpu = 240000000L
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps =
	tzapu/WiFiManager@2.0.17
	olikraus/U8g2@2.36.5
	bblanchon/ArduinoJson@7.2.2
	ESP32Async/AsyncTCP@3.4.10
	ESP32Async/ESPAsyncWebServer@3.10.0

[env:esp32dev]
extends = common

[env:cyd]
extends = common
build_flags =
	${common.build_flags}
	-DDISPLAY_CYD
	-DUSER_SETUP_LOADED
	-DILI9341_DRIVER
	-DTFT_WIDTH=240
	-DTFT_HEIGHT=320
	-DTFT_MISO=12
	-DTFT_MOSI=13
	-DTFT_SCLK=14
	-DTFT_CS=15
	-DTFT_DC=2
	-DTFT_RST=-1
	-DTFT_RGB_ORDER=TFT_BGR
lib_deps =
	${common.lib_deps}
	bodmer/TFT_eSPI@2.5.43
	https://github.com/PaulStoffregen/XPT2046_Touchscreen.git